// GENERATED by scripts/generate-redirects.mjs from public/_redirects — do not edit.
export default {
  "/rv-battery-voltage/": {
    "to": "/posts/rv-battery-voltage/",
    "status": 301
  },
  "/rv-battery-voltage": {
    "to": "/posts/rv-battery-voltage/",
    "status": 301
  },
  "/lithium-rv-batteries/": {
    "to": "/posts/best-lithium-ion-rv-batteries/",
    "status": 301
  },
  "/lithium-rv-batteries": {
    "to": "/posts/best-lithium-ion-rv-batteries/",
    "status": 301
  },
  "/motorhome-battery-guide/": {
    "to": "/posts/motorhome-battery-guide/",
    "status": 301
  },
  "/motorhome-battery-guide": {
    "to": "/posts/motorhome-battery-guide/",
    "status": 301
  },
  "/guide-to-charge-your-rv-battery/": {
    "to": "/posts/guide-to-charge-your-rv-battery/",
    "status": 301
  },
  "/guide-to-charge-your-rv-battery": {
    "to": "/posts/guide-to-charge-your-rv-battery/",
    "status": 301
  },
  "/best-lithium-ion-rv-batteries/": {
    "to": "/posts/best-lithium-ion-rv-batteries/",
    "status": 301
  },
  "/best-lithium-ion-rv-batteries": {
    "to": "/posts/best-lithium-ion-rv-batteries/",
    "status": 301
  },
  "/best-rv-batteries-for-boondocking/": {
    "to": "/posts/best-rv-batteries-for-boondocking/",
    "status": 301
  },
  "/best-rv-batteries-for-boondocking": {
    "to": "/posts/best-rv-batteries-for-boondocking/",
    "status": 301
  },
  "/electric-bike-vs-standard-bicycle-pedaling/": {
    "to": "/posts/electric-bike-vs-standard-bicycle-pedaling/",
    "status": 301
  },
  "/electric-bike-vs-standard-bicycle-pedaling": {
    "to": "/posts/electric-bike-vs-standard-bicycle-pedaling/",
    "status": 301
  },
  "/cross-country-ebikes/": {
    "to": "/posts/cross-country-ebikes/",
    "status": 301
  },
  "/cross-country-ebikes": {
    "to": "/posts/cross-country-ebikes/",
    "status": 301
  },
  "/best-starter-e-bikes-for-beginners/": {
    "to": "/posts/best-starter-e-bikes-for-beginners/",
    "status": 301
  },
  "/best-starter-e-bikes-for-beginners": {
    "to": "/posts/best-starter-e-bikes-for-beginners/",
    "status": 301
  },
  "/single-battery-ebike-vs-dual-battery-ebike/": {
    "to": "/posts/single-battery-ebike-vs-dual-battery-ebike/",
    "status": 301
  },
  "/single-battery-ebike-vs-dual-battery-ebike": {
    "to": "/posts/single-battery-ebike-vs-dual-battery-ebike/",
    "status": 301
  },
  "/9-best-electric-bike-trailers/": {
    "to": "/posts/9-best-electric-bike-trailers/",
    "status": 301
  },
  "/9-best-electric-bike-trailers": {
    "to": "/posts/9-best-electric-bike-trailers/",
    "status": 301
  },
  "/when-to-buy-discounted-ebike-batteries/": {
    "to": "/posts/ebike-battery-replacement-cost-guide/",
    "status": 301
  },
  "/when-to-buy-discounted-ebike-batteries": {
    "to": "/posts/ebike-battery-replacement-cost-guide/",
    "status": 301
  },
  "/cart-batteries-in-rvstion/": {
    "to": "/posts/can-i-use-a-car-battery-in-my-rv/",
    "status": 301
  },
  "/cart-batteries-in-rvstion": {
    "to": "/posts/can-i-use-a-car-battery-in-my-rv/",
    "status": 301
  },
  "/best-lithium-batteries-for-rv-boondocking/": {
    "to": "/posts/best-lithium-batteries-for-rv-boondocking/",
    "status": 301
  },
  "/best-lithium-batteries-for-rv-boondocking": {
    "to": "/posts/best-lithium-batteries-for-rv-boondocking/",
    "status": 301
  },
  "/best-folding-ebikes-for-rv/": {
    "to": "/posts/best-folding-ebikes-for-rv/",
    "status": 301
  },
  "/best-folding-ebikes-for-rv": {
    "to": "/posts/best-folding-ebikes-for-rv/",
    "status": 301
  },
  "/e-bike-vs-e-scooter/": {
    "to": "/posts/e-bike-vs-e-scooter/",
    "status": 301
  },
  "/e-bike-vs-e-scooter": {
    "to": "/posts/e-bike-vs-e-scooter/",
    "status": 301
  },
  "/rv-battery-not-holding-charge/": {
    "to": "/posts/rv-battery-not-holding-charge/",
    "status": 301
  },
  "/rv-battery-not-holding-charge": {
    "to": "/posts/rv-battery-not-holding-charge/",
    "status": 301
  },
  "/long-range-ebike-battery/": {
    "to": "/posts/long-range-ebike-battery/",
    "status": 301
  },
  "/long-range-ebike-battery": {
    "to": "/posts/long-range-ebike-battery/",
    "status": 301
  },
  "/best-2000w-ebike-battery-kits/": {
    "to": "/posts/best-2000w-ebike-battery-kits/",
    "status": 301
  },
  "/best-2000w-ebike-battery-kits": {
    "to": "/posts/best-2000w-ebike-battery-kits/",
    "status": 301
  },
  "/10-best-rv-batteries-under-500/": {
    "to": "/posts/10-best-rv-batteries-under-500/",
    "status": 301
  },
  "/10-best-rv-batteries-under-500": {
    "to": "/posts/10-best-rv-batteries-under-500/",
    "status": 301
  },
  "/battleborn-vs-renogy/": {
    "to": "/posts/battleborn-vs-renogy/",
    "status": 301
  },
  "/battleborn-vs-renogy": {
    "to": "/posts/battleborn-vs-renogy/",
    "status": 301
  },
  "/rv-battery-bank-sizing-calculator/": {
    "to": "/posts/rv-battery-bank-sizing-calculator/",
    "status": 301
  },
  "/rv-battery-bank-sizing-calculator": {
    "to": "/posts/rv-battery-bank-sizing-calculator/",
    "status": 301
  },
  "/12v-vs-24v-rv-batteries/": {
    "to": "/posts/12v-vs-24v-rv-batteries/",
    "status": 301
  },
  "/12v-vs-24v-rv-batteries": {
    "to": "/posts/12v-vs-24v-rv-batteries/",
    "status": 301
  },
  "/wire-multiple-rv-batteries/": {
    "to": "/posts/rv-dual-battery-setup/",
    "status": 301
  },
  "/wire-multiple-rv-batteries": {
    "to": "/posts/rv-dual-battery-setup/",
    "status": 301
  },
  "/why-your-ebike-battery-wont-charge/": {
    "to": "/posts/ebike-battery-not-charging/",
    "status": 301
  },
  "/why-your-ebike-battery-wont-charge": {
    "to": "/posts/ebike-battery-not-charging/",
    "status": 301
  },
  "/how-to-test-ebike-battery-health/": {
    "to": "/posts/how-to-test-ebike-battery-health/",
    "status": 301
  },
  "/how-to-test-ebike-battery-health": {
    "to": "/posts/how-to-test-ebike-battery-health/",
    "status": 301
  },
  "/connect-two-12v-rv-batteries/": {
    "to": "/posts/rv-dual-battery-setup/",
    "status": 301
  },
  "/connect-two-12v-rv-batteries": {
    "to": "/posts/rv-dual-battery-setup/",
    "status": 301
  },
  "/best-100ah-rv-batteries/": {
    "to": "/posts/best-100ah-rv-batteries/",
    "status": 301
  },
  "/best-100ah-rv-batteries": {
    "to": "/posts/best-100ah-rv-batteries/",
    "status": 301
  },
  "/rv-dual-battery-setup/": {
    "to": "/posts/rv-dual-battery-setup/",
    "status": 301
  },
  "/rv-dual-battery-setup": {
    "to": "/posts/rv-dual-battery-setup/",
    "status": 301
  },
  "/ebike-battery-connector-types/": {
    "to": "/posts/ebike-battery-connector-types/",
    "status": 301
  },
  "/ebike-battery-connector-types": {
    "to": "/posts/ebike-battery-connector-types/",
    "status": 301
  },
  "/rv-ebike-charging-guide/": {
    "to": "/posts/rv-ebike-charging-solar/",
    "status": 301
  },
  "/rv-ebike-charging-guide": {
    "to": "/posts/rv-ebike-charging-solar/",
    "status": 301
  },
  "/best-ebike-carriers-for-your-rv/": {
    "to": "/posts/best-ebike-carriers-for-your-rv/",
    "status": 301
  },
  "/best-ebike-carriers-for-your-rv": {
    "to": "/posts/best-ebike-carriers-for-your-rv/",
    "status": 301
  },
  "/rv-solar-battery-setup/": {
    "to": "/posts/rv-solar-battery-setup/",
    "status": 301
  },
  "/rv-solar-battery-setup": {
    "to": "/posts/rv-solar-battery-setup/",
    "status": 301
  },
  "/top-10-ebike-batteries-for-senior-riders/": {
    "to": "/posts/long-range-ebike-battery/",
    "status": 301
  },
  "/top-10-ebike-batteries-for-senior-riders": {
    "to": "/posts/long-range-ebike-battery/",
    "status": 301
  },
  "/offroad-ebike-battery-protection/": {
    "to": "/posts/offroad-ebike-battery-protection/",
    "status": 301
  },
  "/offroad-ebike-battery-protection": {
    "to": "/posts/offroad-ebike-battery-protection/",
    "status": 301
  },
  "/waterproof-ebike-battery-cases/": {
    "to": "/posts/offroad-ebike-battery-protection/",
    "status": 301
  },
  "/waterproof-ebike-battery-cases": {
    "to": "/posts/offroad-ebike-battery-protection/",
    "status": 301
  },
  "/rv-smart-bluetooth-batteries/": {
    "to": "/posts/rv-battery-monitoring-system/",
    "status": 301
  },
  "/rv-smart-bluetooth-batteries": {
    "to": "/posts/rv-battery-monitoring-system/",
    "status": 301
  },
  "/boondocking-with-e-bikes/": {
    "to": "/posts/boondocking-with-e-bikes/",
    "status": 301
  },
  "/boondocking-with-e-bikes": {
    "to": "/posts/boondocking-with-e-bikes/",
    "status": 301
  },
  "/rv-battery-in-winter/": {
    "to": "/posts/rv-battery-in-winter/",
    "status": 301
  },
  "/rv-battery-in-winter": {
    "to": "/posts/rv-battery-in-winter/",
    "status": 301
  },
  "/solar-charging-rv-batteries/": {
    "to": "/posts/rv-solar-battery-setup/",
    "status": 301
  },
  "/solar-charging-rv-batteries": {
    "to": "/posts/rv-solar-battery-setup/",
    "status": 301
  },
  "/rv-battery-monitor-installation/": {
    "to": "/posts/rv-battery-monitoring-system/",
    "status": 301
  },
  "/rv-battery-monitor-installation": {
    "to": "/posts/rv-battery-monitoring-system/",
    "status": 301
  },
  "/litime-vs-battle-born-batteries/": {
    "to": "/posts/litime-vs-battle-born-batteries/",
    "status": 301
  },
  "/litime-vs-battle-born-batteries": {
    "to": "/posts/litime-vs-battle-born-batteries/",
    "status": 301
  },
  "/quietkat-vs-rad-power-battery/": {
    "to": "/posts/quietkat-vs-rad-power-battery/",
    "status": 301
  },
  "/quietkat-vs-rad-power-battery": {
    "to": "/posts/quietkat-vs-rad-power-battery/",
    "status": 301
  },
  "/which-is-best-for-your-rv-the-renology-or-goal-zero-rv-batteries/": {
    "to": "/posts/best-lithium-ion-rv-batteries/",
    "status": 301
  },
  "/which-is-best-for-your-rv-the-renology-or-goal-zero-rv-batteries": {
    "to": "/posts/best-lithium-ion-rv-batteries/",
    "status": 301
  },
  "/lithium-battery-warranty-comparison-rv/": {
    "to": "/posts/lithium-battery-warranty-comparison-rv/",
    "status": 301
  },
  "/lithium-battery-warranty-comparison-rv": {
    "to": "/posts/lithium-battery-warranty-comparison-rv/",
    "status": 301
  },
  "/ebike-battery-replacement-cost-guide/": {
    "to": "/posts/ebike-battery-replacement-cost-guide/",
    "status": 301
  },
  "/ebike-battery-replacement-cost-guide": {
    "to": "/posts/ebike-battery-replacement-cost-guide/",
    "status": 301
  },
  "/rv-battery-monitoring-system/": {
    "to": "/posts/rv-battery-monitoring-system/",
    "status": 301
  },
  "/rv-battery-monitoring-system": {
    "to": "/posts/rv-battery-monitoring-system/",
    "status": 301
  },
  "/trojan-t-105-vs-lithium-batteries/": {
    "to": "/posts/agm-vs-lithium-rv-batteries/",
    "status": 301
  },
  "/trojan-t-105-vs-lithium-batteries": {
    "to": "/posts/agm-vs-lithium-rv-batteries/",
    "status": 301
  },
  "/hybrid-rv-battery-setup/": {
    "to": "/posts/hybrid-rv-battery-setup/",
    "status": 301
  },
  "/hybrid-rv-battery-setup": {
    "to": "/posts/hybrid-rv-battery-setup/",
    "status": 301
  },
  "/lithium-for-your-rv/": {
    "to": "/posts/lithium-for-your-rv/",
    "status": 301
  },
  "/lithium-for-your-rv": {
    "to": "/posts/lithium-for-your-rv/",
    "status": 301
  },
  "/best-rv-batteries-under-500-dollars/": {
    "to": "/posts/best-rv-batteries-under-500-dollars/",
    "status": 301
  },
  "/best-rv-batteries-under-500-dollars": {
    "to": "/posts/best-rv-batteries-under-500-dollars/",
    "status": 301
  },
  "/best-lifepo4-batteries/": {
    "to": "/posts/best-lifepo4-batteries/",
    "status": 301
  },
  "/best-lifepo4-batteries": {
    "to": "/posts/best-lifepo4-batteries/",
    "status": 301
  },
  "/rv-battery-bank-sizing-calculator-guide/": {
    "to": "/posts/rv-battery-bank-sizing-calculator/",
    "status": 301
  },
  "/rv-battery-bank-sizing-calculator-guide": {
    "to": "/posts/rv-battery-bank-sizing-calculator/",
    "status": 301
  },
  "/12v-vs-24v-rv-battery-systems/": {
    "to": "/posts/12v-vs-24v-rv-battery-systems/",
    "status": 301
  },
  "/12v-vs-24v-rv-battery-systems": {
    "to": "/posts/12v-vs-24v-rv-battery-systems/",
    "status": 301
  },
  "/wire-multiple-rv-batteries-series-parallel-guide/": {
    "to": "/posts/rv-dual-battery-setup/",
    "status": 301
  },
  "/wire-multiple-rv-batteries-series-parallel-guide": {
    "to": "/posts/rv-dual-battery-setup/",
    "status": 301
  },
  "/ebike-battery-not-charging/": {
    "to": "/posts/ebike-battery-not-charging/",
    "status": 301
  },
  "/ebike-battery-not-charging": {
    "to": "/posts/ebike-battery-not-charging/",
    "status": 301
  },
  "/test-ebike-battery-health-without-tools/": {
    "to": "/posts/how-to-test-ebike-battery-health/",
    "status": 301
  },
  "/test-ebike-battery-health-without-tools": {
    "to": "/posts/how-to-test-ebike-battery-health/",
    "status": 301
  },
  "/how-to-connect-two-12v-rv-batteries/": {
    "to": "/posts/rv-dual-battery-setup/",
    "status": 301
  },
  "/how-to-connect-two-12v-rv-batteries": {
    "to": "/posts/rv-dual-battery-setup/",
    "status": 301
  },
  "/100ah-rv-battery/": {
    "to": "/posts/best-100ah-rv-batteries/",
    "status": 301
  },
  "/100ah-rv-battery": {
    "to": "/posts/best-100ah-rv-batteries/",
    "status": 301
  },
  "/e-bike-battery-connector-types/": {
    "to": "/posts/ebike-battery-connector-types/",
    "status": 301
  },
  "/e-bike-battery-connector-types": {
    "to": "/posts/ebike-battery-connector-types/",
    "status": 301
  },
  "/rv-ebike-charging-solar/": {
    "to": "/posts/rv-ebike-charging-solar/",
    "status": 301
  },
  "/rv-ebike-charging-solar": {
    "to": "/posts/rv-ebike-charging-solar/",
    "status": 301
  },
  "/ebike-carriers-for-rv-rack/": {
    "to": "/posts/best-ebike-carriers-for-your-rv/",
    "status": 301
  },
  "/ebike-carriers-for-rv-rack": {
    "to": "/posts/best-ebike-carriers-for-your-rv/",
    "status": 301
  },
  "/sitemap.xml": {
    "to": "/sitemap-index.xml",
    "status": 301
  },
  "/sitemap.xml/": {
    "to": "/sitemap-index.xml",
    "status": 301
  },
  "/posts/100ah-rv-battery": {
    "to": "/posts/best-100ah-rv-batteries/",
    "status": 301
  },
  "/posts/100ah-rv-battery/": {
    "to": "/posts/best-100ah-rv-batteries/",
    "status": 301
  },
  "/posts/cart-batteries-in-rvstion": {
    "to": "/posts/can-i-use-a-car-battery-in-my-rv/",
    "status": 301
  },
  "/posts/cart-batteries-in-rvstion/": {
    "to": "/posts/can-i-use-a-car-battery-in-my-rv/",
    "status": 301
  },
  "/posts/connect-two-12v-rv-batteries": {
    "to": "/posts/rv-dual-battery-setup/",
    "status": 301
  },
  "/posts/connect-two-12v-rv-batteries/": {
    "to": "/posts/rv-dual-battery-setup/",
    "status": 301
  },
  "/posts/ebike-carriers-for-rv-rack": {
    "to": "/posts/best-ebike-carriers-for-your-rv/",
    "status": 301
  },
  "/posts/ebike-carriers-for-rv-rack/": {
    "to": "/posts/best-ebike-carriers-for-your-rv/",
    "status": 301
  },
  "/posts/lithium-rv-batteries": {
    "to": "/posts/best-lithium-ion-rv-batteries/",
    "status": 301
  },
  "/posts/lithium-rv-batteries/": {
    "to": "/posts/best-lithium-ion-rv-batteries/",
    "status": 301
  },
  "/posts/rv-battery-monitor-installation": {
    "to": "/posts/rv-battery-monitoring-system/",
    "status": 301
  },
  "/posts/rv-battery-monitor-installation/": {
    "to": "/posts/rv-battery-monitoring-system/",
    "status": 301
  },
  "/posts/rv-ebike-charging-guide": {
    "to": "/posts/rv-ebike-charging-solar/",
    "status": 301
  },
  "/posts/rv-ebike-charging-guide/": {
    "to": "/posts/rv-ebike-charging-solar/",
    "status": 301
  },
  "/posts/rv-smart-bluetooth-batteries": {
    "to": "/posts/rv-battery-monitoring-system/",
    "status": 301
  },
  "/posts/rv-smart-bluetooth-batteries/": {
    "to": "/posts/rv-battery-monitoring-system/",
    "status": 301
  },
  "/posts/solar-charging-rv-batteries": {
    "to": "/posts/rv-solar-battery-setup/",
    "status": 301
  },
  "/posts/solar-charging-rv-batteries/": {
    "to": "/posts/rv-solar-battery-setup/",
    "status": 301
  },
  "/posts/test-ebike-battery-health-without-tools": {
    "to": "/posts/how-to-test-ebike-battery-health/",
    "status": 301
  },
  "/posts/test-ebike-battery-health-without-tools/": {
    "to": "/posts/how-to-test-ebike-battery-health/",
    "status": 301
  },
  "/posts/top-10-ebike-batteries-for-senior-riders": {
    "to": "/posts/long-range-ebike-battery/",
    "status": 301
  },
  "/posts/top-10-ebike-batteries-for-senior-riders/": {
    "to": "/posts/long-range-ebike-battery/",
    "status": 301
  },
  "/posts/trojan-t-105-vs-lithium-batteries": {
    "to": "/posts/agm-vs-lithium-rv-batteries/",
    "status": 301
  },
  "/posts/trojan-t-105-vs-lithium-batteries/": {
    "to": "/posts/agm-vs-lithium-rv-batteries/",
    "status": 301
  },
  "/posts/waterproof-ebike-battery-cases": {
    "to": "/posts/offroad-ebike-battery-protection/",
    "status": 301
  },
  "/posts/waterproof-ebike-battery-cases/": {
    "to": "/posts/offroad-ebike-battery-protection/",
    "status": 301
  },
  "/posts/when-to-buy-discounted-ebike-batteries": {
    "to": "/posts/ebike-battery-replacement-cost-guide/",
    "status": 301
  },
  "/posts/when-to-buy-discounted-ebike-batteries/": {
    "to": "/posts/ebike-battery-replacement-cost-guide/",
    "status": 301
  },
  "/posts/which-is-best-for-your-rv-the-renology-or-goal-zero-rv-batteries": {
    "to": "/posts/best-lithium-ion-rv-batteries/",
    "status": 301
  },
  "/posts/which-is-best-for-your-rv-the-renology-or-goal-zero-rv-batteries/": {
    "to": "/posts/best-lithium-ion-rv-batteries/",
    "status": 301
  },
  "/posts/why-your-ebike-battery-wont-charge": {
    "to": "/posts/ebike-battery-not-charging/",
    "status": 301
  },
  "/posts/why-your-ebike-battery-wont-charge/": {
    "to": "/posts/ebike-battery-not-charging/",
    "status": 301
  },
  "/posts/wire-multiple-rv-batteries": {
    "to": "/posts/rv-dual-battery-setup/",
    "status": 301
  },
  "/posts/wire-multiple-rv-batteries/": {
    "to": "/posts/rv-dual-battery-setup/",
    "status": 301
  }
};
